name: Deploy docs

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
      runs-on: ubuntu-latest
    
      steps:
        
      - name: Deploy docs
        # 发布文档 
        # 推送dist的目录文件到对应存储桶，强制同步
        # run: ossutil sync -f ./docs/.vuepress/dist/ oss://sqwatermark/resguide/
        run: ossutil help
